# Generated by Django 5.2.12 on 2026-04-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', "J'aime"), ('comment', 'Commentaire'), ('follow', 'Abonnement'), ('share', 'Partage')], max_length=20),
        ),
    ]
